services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: board-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - db

  web:
    image: nginx:stable-alpine
    container_name: board-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: board-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board_api
      MYSQL_USER: board
      MYSQL_PASSWORD: boardpass
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: